### ISSUE TITLE
User Registration

### ISSUE THREAD

**Issue by kyrregjerstad** [Pgarza-dev/Noroff-JS-2#11]
### User Story

_As a potential user with an email address ending in @noroff.no or @stud.noroff.no,  
I want to register a profile on the platform,  
So that I can access and interact with the social media app._

#### Note: 
Initial implementation will focus on core functionality, with styling to be applied in a later development phase.

---

### Acceptance Criteria

1. **UI Visibility**: A "Register" button should be accessible from the landing page.
2. **Form Components**: The registration form must include fields for email, password, confirm password, and username.
3. **Email Validation**: The system should validate that the email ends with @noroff.no or @stud.noroff.no.
4. **Password Matching**: Password and Confirm Password fields should match.
5. **Successful Registration**: Redirect the user to the login page.

---

### Requirements Checklist

- [x] **Form Fields**: Implement fields for Email, Password, Confirm Password, and Username.
- [x] **Email Validation**: Use JavaScript to ensure the email address ends with @noroff.no or @stud.noroff.no.
- [x] **Password Matching**: Use JavaScript to validate that the "Password" and "Confirm Password" fields match.
- [x] **API Interaction**: Make a POST request to the API with the registration data.
- [x] **Redirection**: Redirect to login page upon successful registration.

**Comment by Pgarza-dev** [comment]
done!
