### ISSUE TITLE
Profile/others-profile

### ISSUE THREAD

**Issue by kyrregjerstad** [Pgarza-dev/Noroff-JS-2#20]
### User Story

_As a logged-in user,  
I want to view other users' profiles,  
So that I can learn more about them._

---

### Acceptance Criteria

1. **User Navigation**: Should be able to click on a username to view their profile.
2. **Profile Display**: Other users' details and their posts should be visible on the profile page.
3. **Follow**: a user should be able to follow/unfollow a user on their profile page.

---

### Requirements Checklist

- [x] **Profile Page**: Navigate to another user's profile page via clicking on a username.
- [x] **API Interaction**: 
   - [x] Fetch and display the user's avatar, if no avatar is available display a default one
   - [x] Fetch and display the user's banner, if no banner is available display a default one
   - [x] Fetch and display the amount of followers and following
   - [x] When clicking on the follow/unfollow button, send the correct request to the API
   - [x] **Data Display**: Show the retrieved details and posts.

**Comment by Pgarza-dev** [comment]
done!
