### ISSUE TITLE
Clicking on the 'Or register?' link leads to a STATUS_BREAKPOINT

### ISSUE THREAD

**Issue by Melisa-Zorraindo** [Pgarza-dev/Noroff-JS-2#86]
**Description:**

When clicking on the 'Or register?' link from the login page, I encounter a STATUS_BREAKPOINT error. A simple page refresh solves the issue, and the register page loads correctly.

**Comment by kyrregjerstad** [comment]
Hi @Melisa-Zorraindo, thanks for reporting! Could you please check again if you get the same error? I think https://github.com/Pgarza-dev/Noroff-JS-2/pull/83 should have solved it 🤞

**Comment by Melisa-Zorraindo** [comment]
I'm still getting the error, unfortunately. The same error occurs if (after refreshing the register page to load correctly) I click on the 'Already a member?' link. I have opened the site in an incognito window as Chrome suggests, to make sure there aren't any caching issues from my side, but I still encounter the problem.

**Comment by kyrregjerstad** [comment]
@Melisa-Zorraindo  okay, it seems like a strange CSS bug caused it, please let me know if you're still facing the issue! :)
PR: https://github.com/Pgarza-dev/Noroff-JS-2/pull/90

**Comment by Melisa-Zorraindo** [comment]
It's solved now, good job!
